export const bikes = [
    {
        name: "Vintage Eco",
        type: "miejski",
        producer: "Romet",
        wheelSize: 26,
        frameSize: 56,
        weight: 15.3,
        price: 50,
        info: "Czarna elegancja. Idealny do jazdy po mieście, nawet w garniturze.",
        img: "./assets/1.jpg",
        id: 1,
    },
    {
        name: "Pearson",
        type: "szosowy",
        producer: "Romet",
        wheelSize: 28,
        frameSize: 52,
        weight: 10.3,
        price: 55,
        info: "Elegancki? Tak. Szybki? Owszem. Idealny dla zabieganych korposzczurów!",
        img: "./assets/2.jpg",
        id: 2,
    },
    {
        name: "Winner",
        type: "szosowy",
        producer: "Kellys",
        wheelSize: 26,
        frameSize: 52,
        weight: 14.3,
        price: 45,
        info: "Szybki jak błyskawica. Rowerowa wersja Nimbusa 2000. Tym rowerem prześcigniesz każdego!",
        img: "./assets/3.jpg",
        id: 3,
    },
    {
        name: "Snow",
        type: "szosowy",
        producer: "Giant",
        wheelSize: 28,
        frameSize: 54,
        weight: 15.9,
        price: 55,
        info: "Czysta klasyka. Podobno zimą kamuflaż wzrasta - zlewasz się ze śniegiem; uwaga: nie dotyczy żółtej odmiany).",
        img: "./assets/4.jpg",
        id: 4,
    },
    {
        name: "Rainbow",
        type: "miejski",
        producer: "Kellys",
        wheelSize: 24,
        frameSize: 18,
        weight: 16.2,
        price: 40,
        info: "Rower dla każdego marzyciela. Krążą pogłoski, że przy odpowiednim jeźdźcu zmieni się w jednorożca.",
        img: "./assets/5.jpg",
        id: 5,
    },
    {
        name: "Coal",
        type: "szosowy",
        producer: "Romet",
        wheelSize: 26,
        frameSize: 56,
        weight: 14,
        price: 65,
        info: "Czarny rower tylko dla twardzieli. W swoim wyposażeniu nie posiada tylko karabinu maszynowego.",
        img: "./assets/6.jpg",
        id: 6,
    },
    {
        name: "Raspberry",
        type: "miejski",
        producer: "K2",
        wheelSize: 28,
        frameSize: 54,
        weight: 15.3,
        price: 45,
        info: "Jednośladowiec dla prawdziwej księżniczki. Różowy kolor doda Ci uroku, a koszyk pozwoli pomieścić wiele słodkości.",
        img: "./assets/7.jpg",
        id: 7,
    },
    {
        name: "Cloud",
        type: "miejsi",
        producer: "Giant",
        wheelSize: 24,
        frameSize: 50,
        weight: 17.4,
        price: 50,
        info: "Niebieski klasyk. Rower dla typowych normalsów. Znudziły Ci się tramwaje? Polecamy ten rower.",
        img: "./assets/8.jpg",
        id: 8,
    },
    {
        name: "Fire",
        type: "miejski",
        producer: "Kellys",
        wheelSize: 26,
        frameSize: 54,
        weight: 11.2,
        price: 55,
        info: "Rower dla szaleńców. Nigdzie indziej nie wytrenujesz nóg tak szybko jak jadąc na nim.",
        img: "./assets/9.jpg",
        id: 9,
    },
];
