export const bikes = [
    {
        name: "Vintage Eco",
        type: "miejski",
        producer: "Romet",
        wheelSize: 26,
        frameSize: 56,
        weight: 15.3,
        price: 50,
        img: "./assets/1.jpg",
    },
    {
        name: "Pearson",
        type: "szosowy",
        producer: "Romet",
        wheelSize: 28,
        frameSize: 52,
        weight: 10.3,
        price: 55,
        img: "./assets/2.jpg",
    },
    {
        name: "Winner",
        type: "szosowy",
        producer: "Kellys",
        wheelSize: 26,
        frameSize: 52,
        weight: 14.3,
        price: 45,
        img: "./assets/3.jpg",
    },
    {
        name: "Snow",
        type: "szosowy",
        producer: "Giant",
        wheelSize: 28,
        frameSize: 54,
        weight: 15.9,
        price: 55,
        img: "./assets/4.jpg",
    },
    {
        name: "Rainbow",
        type: "miejski",
        producer: "Kellys",
        wheelSize: 24,
        frameSize: 18,
        weight: 16.2,
        price: 40,
        img: "./assets/5.jpg",
    },
    {
        name: "Coal",
        type: "szosowy",
        producer: "Romet",
        wheelSize: 26,
        frameSize: 56,
        weight: 14,
        price: 65,
        img: "./assets/6.jpg",
    },
    {
        name: "Raspberry",
        type: "miejski",
        producer: "K2",
        wheelSize: 28,
        frameSize: 54,
        weight: 15.3,
        price: 45,
        img: "./assets/7.jpg",
    },
    {
        name: "Cloud",
        type: "miejsi",
        producer: "Giant",
        wheelSize: 24,
        frameSize: 50,
        weight: 17.4,
        price: 50,
        img: "./assets/8.jpg",
    },
    {
        name: "Fire",
        type: "miejski",
        producer: "Kellys",
        wheelSize: 26,
        frameSize: 54,
        weight: 11.2,
        price: 55,
        img: "./assets/9.jpg",
    },
];
